title: Some short lectures
description: DESCRIPTION
theme: just-the-docs

url: https://pnathanoj.github.io/someinfo

aux_links: # remove if you don't want this link to appear on your pages
  Template Repository: https://github.com/pnathanoj/someinfo
